//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaSach.Model.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string TEN { get; set; }
        public Nullable<System.DateTime> NGAYLAMVIEC { get; set; }
        public string CHUCVU { get; set; }
    }
}
