//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaSach.Model.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGTINXUATBAN
    {
        public string MASACH { get; set; }
        public Nullable<int> LANTAIBAN { get; set; }
        public Nullable<System.DateTime> NAMXUATBAN { get; set; }
        public string NHAXUATBAN { get; set; }
        public Nullable<int> GIABIA { get; set; }
    
        public virtual SACH SACH { get; set; }
    }
}
